trigger:
  - master

pool:
  vmImage: 'windows-latest'

steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '= 2.5'
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        gem install bundler
        bundle install
        bundle exec cucumber

  - task: PublishCucumberReport@1
    inputs:
      jsonDir: '$(System.DefaultWorkingDirectory)'
      outputPath: '$(Sytem.DefaultWorkingDirectory)'
      theme: 'bootstrap'
      reportSuiteAsScenarios: true
